var asTrefle : (Color, Value) = (Color.allColors[1], Value.allValues[12])
print(asTrefle.1, "de" ,asTrefle.0)
let card1 = Card(color : Color.Pique, value : Value.As)
let card2 = Card(color: Color.Carreau, value :Value.Deux)
let card3 = Card(color : Color.Pique, value : Value.As)
print(card1)
print(card2)
print(card1.isEqual(card2))
print(card1 == card3)
print(Deck.allCards)
var deck1 = Deck.allCards
deck1.shuffle()
print(deck1)
print(deck1.count)
